### ISSUE TITLE
UnicodeDecodeError while installing on windows using python3.5

### ISSUE THREAD

**Issue by qze841** [capitalone/giraffez#1]
bash-3.1$ pip install giraffez
Collecting giraffez
  Using cached giraffez-1.0.0.dev0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\qze841\AppData\Local\Temp\pip-build-agnajbb9\giraffez\setup.py", line 371, in <module>
        long_description=open("README.rst").read(),
      File "c:\Users\qze841\AppData\Local\Continuum\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2590: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\qze841\AppData\Local\Temp\pip-build-agnajbb9\giraffez\
bash-3.1$ pwd
/c/temp/giraffez
bash-3.1$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 371, in <module>
    long_description=open("README.rst").read(),
  File "c:\Users\qze841\AppData\Local\Continuum\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2636: character maps to <undefined>
bash-3.1$ python --version
Python 3.5.2 :: Anaconda 4.1.1 (64-bit)

**Comment by ChrisRx** [comment]
I believe this is an environment configuration problem with your Python environment.

**Comment by ChrisRx** [comment]
Whoops spoke too soon.  Looks like it is a weirdness with how Windows Python3 deals with open (it defaults to the Windows encoding 1252 for some reason).  The first thing that can be done is removing the offending characters (some "fancy" double quotes creeped in via copy/paste).  The other thing is using the io module in this particular case to use the encoding keyword to enforce reading as 'utf-8' instead of 'windows-1252'.

**Comment by qze841** [comment]
thank you!
