### ISSUE TITLE
Substring error

### ISSUE THREAD

**Issue by Foley-CJ** [capitalone/giraffez#10]
I seem to be having a problem using the substring command.  Simplified code as follows:

    import giraffez
    query1 = ''' select SUBSTRING('world' ,1,3) as hello'''
    with giraffez.Cmd() as cmd:
        results = cmd.execute_one(query1)

Any help or insight would be greatly appreciated!

**Comment by ChrisRx** [comment]
The `SUBSTRING` and `SUBSTR` commands are different.  See here:

http://www.info.teradata.com/HTMLPubs/DB_TTU_15_10/index.html#page/SQL_Reference/B035_1145_151K/SUBSTRING_SUBSTR.html

The query being passed to `execute_one` is not valid Teradata SQL (verified it also gives the same error in SQL Assistant).  Try changing your query to something like `select substring('world' from 1 for 3) as hello`.

This is not a giraffez issue so closing unless there

**Comment by Foley-CJ** [comment]
Thanks for the quick reply Chris.  I'm a little confused,  I tested both of the following in Teradata and they worked perfectly fine for me.

     select SUBSTRING('world' ,1,3) as hello
 
     select SUBSTR('world',1,3) as hello

Each query returned 1 column with 1 row labelled as "hello" and populated with the value "wor".
