### ISSUE TITLE
Please add SPDX lines in license headers. 

### ISSUE THREAD

**Issue by SanthiSridharan** [capitalone/giraffez#24]
Include the following lines in the license headers within the scripts. This is to ensure that the automated license scanning tools can identify the license.

SPDX-Copyright: Copyright (c) Capital One Services, LLC
SPDX-License-Identifier: Apache-2.0

**Comment by ChrisRx** [comment]
When you say scripts, do you mean source files?  Does that mean all of the source files that currently have a license header?  If automated license scanning tools are the target for this, then this seems excessive to put this license expression in every source file.  Some cursory research shows that SPDX can be implemented by putting tag:value (which is the format you appear to have above) in a file called `LICENSE.spdx`.

https://github.com/capitalone/cloud-custodian/issues/867: it appear to also have quite a few questions/concerns about this request as well.

**Comment by mudunzl** [comment]
i installed giraffez successfully. I can run import giraffez from python comand line; however, when i tried to use Giraffez command. It  tells me 'coomand not found' . what else should I set up for using giraffez command line?

**Comment by ChrisRx** [comment]
Haven't heard back.  Closing.
