### ISSUE TITLE
pip install fails on mac os 

### ISSUE THREAD

**Issue by marksibrahim** [capitalone/giraffez#25]
In file included from giraffez/cli/cmdobject.c:18:
giraffez/cli/cmdobject.h:37:10: fatal error: 'dbcarea.h' file not found
#include <dbcarea.h>
         ^
1 error generated.
error: command 'clang' failed with exit status 1

**Comment by ChrisRx** [comment]
Do you have the Teradata CLIv2 and Teradata Parallel Transporter API currently installed?  Without these the pip install will not succeed.

The particular file in the error message is one of the CLIv2 files, provided by Teradata, that is not being found on your system during installation (it isn't in the include path that `setup.py` is looking for it).  Another question, do you have it installed but in a non-standard location?

**Comment by marksibrahim** [comment]
@ChrisRx thanks for the clarification. I'm not able to locate the requirements for Mac: Teradata doesn't seem to provide a download even with a login. Where does giraffez recommend we obtain these requirements?

**Comment by ChrisRx** [comment]
Unfortunately these are proprietary drivers that Teradata chooses not to share my broadly on their website.  Internally we have these available as part of licensing the Teradata database software, so unless you are paid customer you are not going to be able to get them from Teradata.  You can, however, try to send them a support message or possibly post this on their forums to see if they can provide an answer for you.

**Comment by marksibrahim** [comment]
I see, that's unfortunate. That explains what's going on though. Thanks @ChrisRx
