### ISSUE TITLE
'bigint' data type overflows on Windows platforms

### ISSUE THREAD

**Issue by bendybus** [capitalone/giraffez#26]
Hi - When I export bigint fields the exported value does not match the table value.

The steps to recreate the problem are below.

Teradata Code:
```sql
create table nztemp.contains_a_bigint( bigint_field bigint not null) no primary index;
insert into nztemp.contains_a_bigint (bigint_field) values (9111200007015236);
```

Python Code:
```python
import giraffez

with giraffez.Export('nztemp.contains_a_bigint',
                     host='my_host',
                     username='my_user',
                     password='my_password',
                     delimiter='\t',
                     null='',
                     encoding='dict') as export:
    for row in export.results():
        print row
        
>>> {'bigint_field': -1880798396L}
```

Of course I was expecting 9111200007015236. 

Any help would be appreciated.

**Comment by bendybus** [comment]
My versions for reference:
* giraffez: 1.1.7
* Teradata: 14:10
* TPT: 15.10.01.02
* Python: 2.7.12

**Comment by ChrisRx** [comment]
What Operating System and Platform/Arch (like x86-64, i386, arm, etc) is the system you are running giraffez ?  I suspect this might have something to do with the default word size for a given platform, since it your test produces the correct result on my system.

**Comment by ChrisRx** [comment]
The other thing that might be helpful to track this down: when you run that with encoding="text", does it produce the correct result?

**Comment by bendybus** [comment]
I can confirm that the encoding = "text" returns the same result.  

My OS is Windows 10 - 64 bit, Python is also the 64 bit version.

I can see that the result of get_buffer_str() / get_buffer_dict() have the incorrect result, but at that point it hits the C code which I cannot debug.  I was wondering if something untoward was happening in the unpack_int64_t function of unpack.c.  

I am happy to run any debug code if that helps.

**Comment by bendybus** [comment]
I just realised that I was unclear... I should have said I can confirm that the encoding = "text" returns the same (incorrect) result.

**Comment by ChrisRx** [comment]
There is nothing "untoward" happening in the unpack_int64_t function, it is the canonical way of unpacking a stream of bytes into a C numeric type (each byte is shifted into the position that would make up the value of the new integer until the buffer is exhausted).

However, I did a few quick tests and the reason the result is correct on linux/mac platforms and not yours is, as I expected, how Windows defines a C `long`.  I'm going to do a bit more testing, but I should have a fix for this up sometime tomorrow morning that ensures that Windows compilers use the correct size for 64-bit integers and don't overflow (which is what you are experiencing).  Let me know if you experience anything else like this and I can fix it right away.  I don't have a lot of Windows users that can report back bugs of this nature, so these are extremely valuable.

**Comment by bendybus** [comment]
Brilliant I will give it a shot once I see a fix (plus a time-shift delay as I am in NZ).  So far I have only tried exporting, but I will have some time to try loading sometime in the next few days and will be happy to report back my findings.  
BTW I really like the concept of giraffez, I have been looking for something like this for a while so thanks.

**Comment by ChrisRx** [comment]
I believe that should fix the issue, let me know if it does not.  Thanks for reporting the bug!

**Comment by bendybus** [comment]
I can confirm that this is now fixed.  
```python
>>> {'bigint_field': 9111200007015236L}
```
Thank you.
