### ISSUE TITLE
error during executing giraffez load out_file.txt database.table

### ISSUE THREAD

**Issue by piotrkuzmiak** [capitalone/giraffez#30]
Hi

I faced problem trying to load data from previously exported file. It is being reported as: "**giraffez.errors.GiraffeTypeError: Column 'cif' does not exist**" what is quite weird (as stated before the file was created via *giraffez export database.table_name output_file.txt -d '\t'*).

Here is the definition of the table:

*CREATE MULTISET TABLE DDHDP01P.AG_KHD_4463_2_BIK_NOWA ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      cif CHAR(19) CHARACTER SET LATIN NOT CASESPECIFIC,
      nr_rachunku_bik INTEGER,
      typ_finansowania CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      data_otwarcia DATE FORMAT 'YYYY-MM-DD',
      przewid_data_zakonczenia DATE FORMAT 'YYYY-MM-DD',
      okres INTEGER,
      waluta CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC,
      kurs CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      status CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      data_zamkniecia DATE FORMAT 'YYYY-MM-DD',
      data_salda_rachunku DATE FORMAT 'YYYY-MM-DD',
      kwota_do_splaty DECIMAL(18,2),
      kwota_kredytu DECIMAL(18,2),
      kwota_raty DECIMAL(18,2),
      data_raportu DATE FORMAT 'YYYY-MM-DD',
      kwota_limitu DECIMAL(18,2),
      kwota_gwarancji DECIMAL(18,2),
      liczba_rat_kapitalowych INTEGER,
      czestotliwosc_splat_kapitalu VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( cif );*

**Peter**

----
giraffez version: 1.1.8
Python version: 3.5.2
OS: Windows 7 Enterprise
Teradata Tools and Utilities version: 15.10.05.00

**Comment by ChrisRx** [comment]
Hey Peter, could you provide the full Python traceback you are receiving and the exact commands you used to both export and load a table?  Potentially not related but I wanted to mention if by chance you are exporting so that you can archive and load later that you should definitely take a look at the giraffez [archive feature](http://www.capitalone.io/giraffez/usage.html#archiving-tables).

**Comment by piotrkuzmiak** [comment]
Hi
Sorry for delay. Below there are commands and their ouputs.

**For exporting (this is OK):** 
giraffez export DDHDP01P.AG_KHD_4463_2_BIK_NOWA output_file.txt -d '\t'
Connection: Connecting to data source 'khd' ...
Connection: Connection to 'khd' established successfully.
Export: Initiating Teradata PT request (awaiting server)  ...
Export: Teradata PT request accepted.
Export: Executing ...
  encoding  => "text"
  delimiter => "'       '"
  null      => "NULL"
  query     => "DDHDP01P.AG_KHD_4463_2_BIK_NOWA"

Export: Processed 69387 rows
Results: 69387 rows in 3.182s
Connection: Closing Teradata connection ...
Export: Closing Teradata PT connection ...
Export: Teradata PT request complete.
Connection: Connection to 'khd' closed.

**For loading previously exported file**:
giraffez load  output_file.txt DDHDP01P.AG_KHD_4463_2_BIK_NOWA 
Connection: Connecting to data source 'khd' ...
Connection: Connection to 'khd' established successfully.
Command: Executing ...
  source     => "output_file.txt"
  output     => "DDHDP01P.AG_KHD_4463_2_BIK_NOWA"
  delimiter  => "       "
  panic      => "False"
  quote char => """
  query      => "select top 1 * from DDHDP01P.AG_KHD_4463_2_BIK_NOWA"
  null       => "NULL"
Connection: Closing Teradata connection ...
Connection: Connection to 'khd' closed.
Traceback (most recent call last):
  File "c:\users\129175\appdata\local\continuum\anaconda3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\129175\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\129175\AppData\Local\Continuum\Anaconda3\Scripts\giraffez.exe\__main__.py", line 9, in <module>
  File "c:\users\129175\appdata\local\continuum\anaconda3\lib\site-packages\giraffez\__main__.py", line 25, in main
    MainCommand().run()
  File "c:\users\129175\appdata\local\continuum\anaconda3\lib\site-packages\giraffez\core.py", line 98, in run
    args.run(args)
  File "c:\users\129175\appdata\local\continuum\anaconda3\lib\site-packages\giraffez\commandline.py", line 377, in run
    date_conversion=date_conversion, quotechar=args.quote_char)
  File "c:\users\129175\appdata\local\continuum\anaconda3\lib\site-packages\giraffez\load.py", line 94, in from_file
    return self.insert(table_name, rows, fields=f.header, date_conversion=date_conversion)
  File "c:\users\129175\appdata\local\continuum\anaconda3\lib\site-packages\giraffez\load.py", line 117, in insert
    columns.set_filter(fields)
  File "c:\users\129175\appdata\local\continuum\anaconda3\lib\site-packages\giraffez\types.py", line 268, in set_filter
    raise GiraffeTypeError("Column '{}' does not exist".format(name))
giraffez.errors.GiraffeTypeError: Column 'cif'' does not exist

**Comment by ChrisRx** [comment]
I'm sorry for the delay in getting back.  I just finished looking at this today and it looks like the rules for the Windows command shell is different than many *nix/OS X shells in how it handles quoting.  Rather than single quotes starting a quoted string, they are received by the Windows shell as literal single quotes.  So the export command you are performing is outputting the header as `cif'       'nr_rachunku_bik' ...` (and the header is what load uses to infer the delimiter and column names).  I think we should probably just remove all quote characters from the command-line delimiter field, but in the interim you can make this work by just removing the quotes in the command to make it look like this:

```giraffez export DDHDP01P.AG_KHD_4463_2_BIK_NOWA output_file.txt -d \t```
