### ISSUE TITLE
Export to Pandas DataFrame and SFrame

### ISSUE THREAD

**Issue by flolas** [capitalone/giraffez#33]
Hi,

It would be good if we can export data to SFrame and Pandas directly from Giraffez.Export. I really want to collaborate to this project!

**Comment by ktravis** [comment]
Hi Felipe, exporting to a Pandas DataFrame can be accomplished by following [this example](http://www.capitalone.io/giraffez/usage.html#working-with-other-packages). I am not familiar with SFrame, but glancing over their docs it seems that reading from a CSV file is a prominent method for loading, so using `giraffez.Export` to make a CSV file (an example of this is available in the previous link) should be a natural method for interfacing with SFrame. If this is not the case, please let us know what can be done to improve the Python API user experience.
