### ISSUE TITLE
[SLES 11 SP4 (x86_64)] not recognizing teradata libs

### ISSUE THREAD

**Issue by piotrkuzmiak** [capitalone/giraffez#39]
Hi

I am still facing exception saying: libpxicu.so cannot open shared object file [...] but required libs are present and environment variables have been set up as follows:
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/teradata/client/15.00/lib64/libcliv2.so"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/teradata/client/15.00/tbuild/lib64/libtelapi.so"
export TERADATA_HOME="/opt/teradata/client"

![obraz](https://user-images.githubusercontent.com/23447827/29534503-8a48bc2c-86b6-11e7-9ca7-631d43616c51.png)

Where should I look for to solve my issue? Any hints?

Peter

**Comment by ChrisRx** [comment]
Here is an example of what a working one I have used previously looks like:

```
export TERADATA_HOME=/opt/teradata/client/15.00
export LD_LIBRARY_PATH=$TERADATA_HOME/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$TERADATA_HOME/tbuild/lib64:$LD_LIBRARY_PATH
export NLSPATH=$TERADATA_HOME/tbuild/msg/%N
export COPERR=/usr/lib
```

I would prepend the path (versus append it like you have) and make sure it is the path and not the filename of the shared object.  The other thing is that TERADATA_HOME is only to help with installation, so it shouldn't matter, but just in case that TERADATA_HOME needs to have the version added if you are going to specify it.  When it isn't set, it will look for the highest version you have in the default Teradata folders, so it is more of a value to override or help that find your Teradata install should it be a non-standard install.

**Comment by piotrkuzmiak** [comment]
Thanks for explanation Chris. After altering paths I was able to create configuration file: .girafferc without any exception being thrown.

Peter

**Comment by piotrkuzmiak** [comment]
Chris
You helped me once with similar issue, above. This time I am trying to set up connection to Teradata using different server and other teradata driver version (15.10). My .bashrc looks like this:
`export PATH=/python/install/anaconda3/bin:$PATH`
`export JAVA_HOME=/usr/jdk64/latest`
`export ODBCINI=~/.odbc.ini`
`export ODBCSYSINI=/opt/teradata/client/15.10/odbc_64`
`export TERADATA_HOME=/opt/teradata/client/15.10`
`export LD_LIBRARY_PATH=$TERADATA_HOME/lib:$LD_LIBRARY_PATH`
`export LD_LIBRARY_PATH=$TERADATA_HOME/tbuild/odbc/lib64:$LD_LIBRARY_PATH`
`export NLSPATH=$TERADATA_HOME/msg/%N`
`export COPERR=/usr/lib`

I am getting the following exception inside ipython:
`Exception: libpxicu.so: wrong ELF class: ELFCLASS32.`

I assume this might refer to server architecture and required libs dedicated for 64b instead of 32b.

I would appreciate for any help.

Peter

**Comment by piotrkuzmiak** [comment]
I close the issue here is what was wrong, my mistake:
`export LD_LIBRARY_PATH=$TERADATA_HOME/lib:$LD_LIBRARY_PATH`
should be:
`export LD_LIBRARY_PATH=$TERADATA_HOME/lib64:$LD_LIBRARY_PATH`

now it works.

Peter
