### ISSUE TITLE
Failure to load libcliv2.dylib on Mac with miniconda

### ISSUE THREAD

**Issue by SteveBronder** [capitalone/giraffez#42]
Attempting to run `import giraffez` produces the following error

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/miniconda3/envs/saul/lib/python3.6/site-packages/giraffez/__init__.py in <module>()
     38 try:
---> 39     from . import _teradata
     40     from . import _teradatapt

ImportError: dlopen(/Users/****/miniconda3/envs/saul/lib/python3.6/site-packages/giraffez/_teradata.cpython-36m-darwin.so, 2): Library not loaded: libcliv2.dylib
  Referenced from: /Users/****/miniconda3/envs/saul/lib/python3.6/site-packages/giraffez/_teradata.cpython-36m-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

~/github/rock/rock/upload_conn.py in <module>()
      8 camelCase indicates function
      9 """
---> 10 import giraffez
     11 
     12 class upload_connector:

~/miniconda3/envs/saul/lib/python3.6/site-packages/giraffez/__init__.py in <module>()
     52 documentation:
     53     http://www.capitalone.io/giraffez/intro.html#environment.
---> 54 """.format(error))
     55 
     56 from ._teradata import TeradataError

Exception: dlopen(/Users/****/miniconda3/envs/saul/lib/python3.6/site-packages/giraffez/_teradata.cpython-36m-darwin.so, 2): Library not loaded: libcliv2.dylib
  Referenced from: /Users/****/miniconda3/envs/saul/lib/python3.6/site-packages/giraffez/_teradata.cpython-36m-darwin.so
  Reason: image not found.

This indicates that either the giraffez C extensions did not compile
correctly, or more likely, there is an issue with the environment or
installation of the Teradata dependencies. Both the Teradata Call-Level
Interface Version 2 and Teradata Parallel Transporter API require
several environment variables to be set to find the shared library
files and error message catalog.

For more information, refer to this section in the giraffez
documentation:
    http://www.capitalone.io/giraffez/intro.html#environment.
```

Using teradata 15.10 with the following enviroment variables set in my `.bash_profile`
```
export TERADATA_HOME=/Library/Application\ Support/teradata/client/15.10
export LD_LIBRARY_PATH=$TERADATA_HOME/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$TERADATA_HOME/tbuild/lib:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=$LD_LIBRARY_PATH
export NLSPATH=$TERADATA_HOME/msg/%N:$NLSPATH
```

Looking at the lib folder in the teradatra folder I see `libcliv2.dylib` so I'm having a hard time interpreting the above error.

Version Info:
```
giraffez: 2.0.17
OS: macOS Sierra Version 10.12.6
Python Version: 3.6.1
```

**Comment by ChrisRx** [comment]
This appears to be an environment configuration issue.  If you have installed and can locate the shared library file (libcliv2.dylib) and are getting that `Library not loaded` message then it usually ends up indicating that something about the library search path OR that something is wrong with the architecture (like 32-bit vs. 64-bit, but I would doubt this is that since macOS will be on mostly the same arch).

I know very little about macOS, but maybe try setting the `DYLD_FALLBACK_LIBRARY_PATH` to something like:

```
export DYLD_FALLBACK_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH
```

And also the NLSPATH doesn't need to append NLSPATH again at the end so you can strip the `:$NLSPATH`.

**Comment by SteveBronder** [comment]
Thanks for your response. Adding 

```
export DYLD_FALLBACK_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH
```

and reinstalling giraffez did not resolve my above issue. Would darwin.so have an issue with the space in the `TERADATA_HOME` variable?
```
TERADATA_HOME=/Library/Application\ Support/teradata/client/15.10
```

**Comment by motivic** [comment]
I had the same issue. I finally managed to find a fix. If you use `otool` to check the link to the dynamic library `libcliv2.dylib`, you may find that there is no path to `libcliv2.dylib` specified. 
```
% otool -L _teradata.cpython-36m-darwin.so
_teradata.cpython-36m-darwin.so:
	libcliv2.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```
This can be fixed using `install_name_tool` (see the [SO discussion here](https://stackoverflow.com/questions/1937232/linking-to-a-dynamic-library-on-a-mac-with-full-path)):

```install_name_tool -change "libcliv2.dylib" "/Library/Application Support/teradata/client/15.10/lib/libcliv2.dylib" _teradata.cpython-36m-darwin.so```

You also need to do this the dynamic libraries `libcliv2.dylib` and `libtelapi.dylib` for `_teradatapt.cpython-36m-darwin.so`.

I wonder if this has anything to do with my upgrading Xcode. My colleagues did not encounter this problem.

**Comment by happyshows** [comment]
@motivic 

I'm seeting the below error when I execute otool command, I couldn't find much info on google where and how to install the specific lib file, Can you point me a direction? Thanks.

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: '_teradata.cpython-36m-darwin.so': No such file or directory
```
