### ISSUE TITLE
BulkExport.to_str() rounds floats 

### ISSUE THREAD

**Issue by behanjc** [capitalone/giraffez#53]
I have data in a table that is float format, but when I use .to_str(), the value gets rounded.

Specifically the value is 9 digits after the decimal like:
0.#########

and gets rounded to 6 after the decimal like:
0.######

Is this intended behavior?

**Comment by ChrisRx** [comment]
I'm not sure of the implications of making this change for different platforms but I believe it may be as simple as changing the format specifier [here](https://github.com/capitalone/giraffez/blob/master/giraffez/src/row.c#L147) from `%f` to `%g`.  The possible issue is other platforms like windows or macos not supporting that format specifier with the same size.  I will take a look and see what I can find.

**Comment by ChrisRx** [comment]
So, I think that setting the format specifier to `%.16g` should help preserve the float precision when using `.to_str()`.  I have that coming in a new version shortly.  I'm going to close the issue, but feel free to reopen should this not address the problem.
