### ISSUE TITLE
Add rowcount to Cursors returned by TeradataCmd.execute

### ISSUE THREAD

**Issue by theandrew168** [capitalone/giraffez#54]
Hello,

First off, thanks for the great tool! My company has a definite interest in utilizing giraffez for our interactions with Teradata. It has been much more pleasant to work with than Teradata's native tooling.

One feature that we desire (and are willing to write a PR for) is to be able to know how many rows were affected by a given operation. We would use this for logging / analytics purposes. Ideally, this would be accomplished by reading a `rowcount` attribute of the [Cursor](https://capitalone.github.io/giraffez/api.html#giraffez.cmd.Cursor) object(s) returned by the [TeradataCmd.execute](https://capitalone.github.io/giraffez/api.html#giraffez.cmd.TeradataCmd.execute) function. The [DB API 2.0](https://www.python.org/dev/peps/pep-0249/#rowcount) mentions such a feature though I know giraffez isn't designed to be PEP-249 compliant.

In browsing Teradata's CLIv2 documentation, I found that ActivityCount gets returned as a field in the SUCCESS parcel. With some basic testing, I found that this parcel does come through the results processed in the [teradata_handle_record](https://github.com/capitalone/giraffez/blob/master/giraffez/src/teradata.c#L328) function. As for how to propagate this value up to a Cursor object, I'm still looking for the best way.

After that bit of background info, here are the questions I hope to explore with this issue:
* Does this capability already exist in giraffez? I've checked both the docs and the source but could have missed something.
* Are you (as the giraffez maintainers) open to this sort of feature?
* If so, do you have any recommendations on how to implement it? I wonder if `teradata_handle_record` would even be a good location given the "purpose" of that function.

Thanks again for your time and the amazing tool!

**Comment by ChrisRx** [comment]
We are definitely open to this sort of feature, but I want to make sure I understand more specifically before I can make any recommendations on how to implement it.  Is the desire to have the row count of affected rows before or after the Cursor is completely exhausted?  In the case of a select query, the ActivityCount may be accurate before reading through the results, although I think I remember trying to add that and it not working consistently as I expected.  This I believe is why we ultimately made the decision to just allow the user to count the rows for select statement returns themselves (not to say a nice property can't be added to do that for you, resetting on each execute for instance).  The information about what rows were deleted or updated may also be returned but I also seem to remember them being inconsistent as well.

I think regardless, this would be a good addition to the code, and fairly easy to implement.  It would involve adding a switch statement [here](https://github.com/capitalone/giraffez/blob/master/giraffez/src/teradata.c#L268) for `PclSUCCESS` and doing something similar to what it is doing with `PclFAILURE` [here](https://github.com/capitalone/giraffez/blob/master/giraffez/src/teradata.c#L291-L293) by creating a [function](https://github.com/capitalone/giraffez/blob/master/giraffez/src/teradata.c#L42) that reads from the data pointer and casts it into the appropriate struct provided by the CLIv2 (`PclSUCCESStype` in `parcel.h`).

So yeah, just let me know your thoughts on what the rowcount property should be (the Cursor keeps up with it if it can, it always returns the ActivityCount, some mix of the two, etc) and we can go from there!

**Comment by ChrisRx** [comment]
Just making sure I capture this, [here](https://github.com/capitalone/giraffez/blob/master/giraffez/src/teradata.c#L70) I noticed `dynamic_result_sets_allowed` is not being set to `'Y'`, which is mentioned in the CLIv2 documentation as possibly needing it.  I think it would be worth seeing what it returns without setting that first since setting the APH response variable for instance might supersede other options.  Unfortunately, I think some experimentation might be necessary here.

**Comment by theandrew168** [comment]
Our specific concern is more with the number of rows affected by internal database actions (inserts, deletes, updates). Having a rowcount available on selects would also be valuable but I understand that Teradata might not know this value until all query records are realized, depending on its implementation. Given that, I'd almost lean toward having the rowcount property always available on the Cursor. Though, perhaps with a documented caveat when dealing with queries that may or may not be lazy? More research will needed, regardless.

In my initial tests, Teradata was at least able to accurately report the number of rows returned by a query containing an explicit record count restriction, such as:
```sql
select * from foo sample 100
```
However, this is a simple case and I'd have to test more complex interactions to see if the accuracy of that ActivityCount parcel field holds up.

Do you have any examples or specifics as to the inconsistencies you ran into when looking into this in the past? It'd be great to have a variety of test cases to look at.

In the meantime, I'll start looking into an implementation based on the advice you gave. I'll also check and see how that `dynamic_result_sets_allowed` flag affects the whole process.

Thanks!

**Comment by theandrew168** [comment]
Glad to see that this feature made it in. Nice work!
