### ISSUE TITLE
Giraffez build fails with Python 3.7

### ISSUE THREAD

**Issue by theandrew168** [capitalone/giraffez#62]
Python 3.7 updated [PyUnicode_AsUTF8](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_AsUTF8) to return a `const char*` instead of a plain `char*`. This breaks the current version of Giraffez due to [teradatapt.hpp#L114](https://github.com/capitalone/giraffez/blob/master/giraffez/src/teradatapt.hpp#L114) since `TConn::AddAttribute` expects a plain `char*`.

The TPT definition for that method is shown here:
`TELAPI_EXPORT void AddAttribute(TD_Attribute, char* value);`

I believe that the simplest fix for this would be to cast away the const-ness of the result returned from PyUnicode_AsUTF8, though a better (and potentially safer, depending on CPython's implementation) approach might be to copy the string into a non-const location before passing to `AddAttribute`. I suppose that ideally the `AddAttribute` method would already expect a `const char*`, but that's not really worth fussing about.

Regardless of the approach that is decided upon, I'm willing to draft up and test a PR.

Thanks,
Andrew D.

**Comment by ChrisRx** [comment]
Thanks for the issue pointing this out!  Let me ask @ktravis about it as well for their opinion and will post back later today.

**Comment by ChrisRx** [comment]
We both didn't see any issue with casting away the const to satisfy the AddAttribute function.  I think that would probably be the easier and still safe approach to setting AddAttribute.
