### ISSUE TITLE
load.py fails at line 258

### ISSUE THREAD

**Issue by clantroopss** [capitalone/giraffez#67]

**Comment by clantroopss** [comment]
(base) C:\MyPythonScript\Automation\excel>giraffez load againutf8.txt P_ADA.BM_T
EMP_ROI_CUSTOMER_TEST1 -y
[97m[1mConnection: [0m[0mConnecting to data source 'db1' ...
[97m[1mConnection: [0m[0mConnection to 'db1' established successfully.
[97m[1mBulkLoad: [0m[0mDropping table 'P_ADA.BM_TEMP_ROI_CUSTOMER_TEST1_wt'.
..
[97m[1mBulkLoad: [0m[0mDropping table 'P_ADA.BM_TEMP_ROI_CUSTOMER_TEST1_log'
...
[97m[1mBulkLoad: [0m[0mDropping table 'P_ADA.BM_TEMP_ROI_CUSTOMER_TEST1_e1'.
..
[97m[1mBulkLoad: [0m[0mDropping table 'P_ADA.BM_TEMP_ROI_CUSTOMER_TEST1_e2'.
..
[97m[1mBulkLoad: [0m[0mExecuting ...
  source      => "againutf8.txt"
  output      => "P_ADA.BM_TEMP_ROI_CUSTOMER_TEST1"
[97m[1mBulkLoad: [0m[0mInitiating Teradata PT request (awaiting server)  ...

[97m[1mBulkLoad: [0m[0mTeradata PT request accepted.
BulkLoad: [0m[0mProcessed 100001 rows[97m[1mConnection: [0m[0mClosing Tera
data connection ...
[97m[1mBulkLoad: [0m[0mClosing Teradata PT connection ...
[97m[1mBulkLoad: [0m[0mTeradata PT request complete.
[97m[1mConnection: [0m[0mConnection to 'db1' closed.
Traceback (most recent call last):
  File "c:\anaconda3\lib\site-packages\giraffez\io.py", line 146, in __iter__
    yield next(self.reader)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\giraffez.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\lib\site-packages\giraffez\__main__.py", line 25, in main
    MainCommand().run()
  File "c:\anaconda3\lib\site-packages\giraffez\core.py", line 80, in run
    args.run(args)
  File "c:\anaconda3\lib\site-packages\giraffez\commandline.py", line 431, in ru
n
    exit_code = load.from_file(args.input_file, delimiter=args.delimiter, null=a
rgs.null, quotechar=args.quote_char, parse_dates=args.parse_dates)
  File "c:\anaconda3\lib\site-packages\giraffez\load.py", line 258, in from_file

    for i, line in enumerate(f, 1):
RuntimeError: generator raised StopIteration

(base) C:\MyPythonScript\Automation\excel>

**Comment by clantroopss** [comment]
The file is in 'utf-8' format with delimiters as '|' and it does read the data field name matches the one in database but then the connection closes

**Comment by ChrisRx** [comment]
What version of Python are you using? and could you run the command again with the flags `-vv` added?
