### ISSUE TITLE
Export.encoding documentation missing 'dict' option

### ISSUE THREAD

**Issue by g24swint** [capitalone/giraffez#9]
The docstring description for the ecoding attribute in the Export class documentation only documents the use of 'text', 'json', and 'archive'. However, in looking at example code and in the export._initiate function, it appears the 'dict' is also support for the 'dict' Python object type.

The 'dict' type is apparently needed for exporting smoothly to DataFrame objects, and so could see wide usage

**Comment by ChrisRx** [comment]
Reopening just so we don't forget to regen the docs then it can be closed again.

**Comment by ktravis** [comment]
Docs regenerated. Thanks!
